### ISSUE TITLE
Design brainstorming for full-width content

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#6860]
Just brainstorming a bit on how we might do more full-width content on the site! How do these options look to folks?

One idea was that all maps might go full width. Or that all images could go full width /only/ below a certain screen size?

![image](https://user-images.githubusercontent.com/24359/69670900-f450d900-1062-11ea-9b75-728deb51d000.png)

![image](https://user-images.githubusercontent.com/24359/69670908-f9ae2380-1062-11ea-9a6f-2f675e0ff89b.png)

**Comment by jywarren** [comment]
The semitransparent sidebar panel would need this kind of markup:

```css
.sidebar-panel {
    background: rgba(255,255,255,0.7);
    padding: 10px;
    border-radius: 5px;
}
```
