### ISSUE TITLE
Improve the styling of Woofmark buttons on pl.org/post

### ISSUE THREAD

**Issue by VladimirMikulic** [publiclab/plots2#7067]
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### :fire: Problem

![Screenshot_20191231_234530](https://user-images.githubusercontent.com/35997844/71635768-b0379200-2c27-11ea-8f1a-16bfd398b936.png)

![Screenshot_20191231_233610](https://user-images.githubusercontent.com/35997844/71635644-892c9080-2c26-11ea-8c9a-6cd92f5f8fa5.png)

As you can see on the image above, we have some serious issues with our new editor on https://publiclab.org/post. Buttons are overflowing its container, disappearing and causing horizontal scroll bars.
It's even worse on mobile devices and this should be patched ASAP.

### 🚩 Goal

![Screenshot_20200102_233239](https://user-images.githubusercontent.com/35997844/71697483-67fba980-2db8-11ea-829d-48cbfc24e385.png)

![Screenshot_20200102_233306](https://user-images.githubusercontent.com/35997844/71697488-6af69a00-2db8-11ea-9706-5a6d6253eacc.png)

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Open** the file plots2/app/assets/stylesheets/style.css

- Line 342, after the comment, add this code:
```css
@media(max-width: 768px) {
  .ple-module-content {
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  
  .ple-module-content .wk-wysiwyg {
      width: 100%;
  }
    
  .ple-content .wk-commands {
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
    max-width: 390px;
  }

  .ple-content .wk-commands .btn {
    display: flex;
    justify-content: center;
    align-items: center;

    min-width: 50px;
    height: 38px;
    background: white;
    margin: 0px;
    border-radius: 0 !important;
    border: 1px solid #ddd;
    border-left: none;
  }
  
  .ple-content .wk-commands button.btn:nth-of-type(1),
  .ple-content .wk-commands .btn:nth-of-type(8) {
      border-left: 1px solid #ddd;
  }
  
  .ple-content .wk-commands .btn:nth-of-type(8),
  .ple-content .wk-commands .btn:nth-of-type(9),
  .ple-content .wk-commands .btn:nth-of-type(10),
  .ple-content .wk-commands a.btn{
      border-top: 0;
  }

  .ple-content .wk-switchboard {
    text-align: center;
    float: none;
  }
}

@media(max-width: 480px) {
    .ple-content .wk-commands {
        max-width: 325px;
    }
    .ple-content .wk-commands .btn {
        min-width: 30px;
        max-width: 43px;
        width: 100%;
    }
}
``` 

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming the first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!
