### ISSUE TITLE
"Environment data" tooltip in '/map' route is unrecognizable/hidden

### ISSUE THREAD

**Issue by jcads** [publiclab/plots2#9348]
"Environment data" tooltip in '/map' route is unrecognizable/hidden due to the banner.
![image](https://user-images.githubusercontent.com/50954098/111940843-b48ceb00-8b0a-11eb-9493-f25b4430cffa.png)

Can be found in: https://publiclab.org/map

## Suggested fix
Add `close` option to banners so that we can see the top section of the map.
![image](https://user-images.githubusercontent.com/50954098/111940992-0b92c000-8b0b-11eb-99b8-ed590d8d4d33.png)

After _removing/closing_ the banner:
![image](https://user-images.githubusercontent.com/50954098/111940244-3d0a8c00-8b09-11eb-8947-dee427c97ab6.png)
_the tooltip can now be seen on the top right_

**Comment by Priyaraj17** [comment]
May I work on it?

**Comment by waridrox** [comment]
By implementing a **cross button** (https://fontawesome.com/v4.7.0/icon/times can be used), this would also make sense in mobile web views.

<img width="296" alt="Screenshot 2021-03-23 at 3 44 03 PM" src="https://user-images.githubusercontent.com/58583793/112130551-9b5d6a80-8bee-11eb-8ed3-5ee4d9977181.png">

**Comment by jywarren** [comment]
Hi, I wanted to reach out to @publiclab/community-reps on this one to highlight this issue. Thanks for pointing it out!

If you look at the banner styling, i agree there should be a relatively easy way to fix it. But is the map absolute positioned, maybe?

Also noting that this banner is kind of unique in that the code is stored in the database and it's not part of the core codebase. So any changes suggested here would be copied into the database to implement the fix. Thanks everyone!!!!

**Comment by RuthNjeri** [comment]
Thanks for raising this issue @jcads.

I do agree with first looking into whether the map is positioned using `absolute` and maybe looking into making its position relative to the banner, if that's not an option, we can work with making changes to the banner via the database.

**Comment by ebarry** [comment]
Thank you for reporting @jcads !
I agree with @RuthNjeri's comment on first looking into how the map is positioned and making its position relative to the banner if possible :smiley:

**Comment by jywarren** [comment]
Hi all! The banner was originally designed at 49 pixels max height, and has some very carefully written media width breaks to push content down at different sizes. Unfortunately media width selectors in CSS don't account for text length, so as text gets to be more than one line, this approach breaks down. The CSS included in the database as part of the banner code is:

```css

#anniversary {
  background:#eef; 
  padding:8px 10px;
  position:fixed;
  top:0; left:0;
  z-index:999;
  width:100%;
  font-size: 13px;
}

#anniversary b {
  color:#335;
}

#anniversary a {
  color:#339;
  text-decoration: underline;
}

#anniversary p {
  color:#115;
  margin:6px;
  padding-right:10px;
}

#anniversary .btn {
  float:right;
}

.body-container {
  margin-top:48px;
}
#header {
  margin-top:48px;
}

@media (max-width: 768px) {
  
  .body-container {
    margin-top:68px;
  }
  #header {
    margin-top:68px;
  }
}

```

Unfortunately as this doesn't account for text, there's even another button hidden on the left as the whole page is overlapped a bit:

![image](https://user-images.githubusercontent.com/24359/121903057-eb336580-ccf5-11eb-8e3f-6ed816c60caa.png)

![image](https://user-images.githubusercontent.com/24359/121904121-ec18c700-ccf6-11eb-86c8-21a0bd05298f.png)

I think that if we want to be able to accommodate any length of content in the banner, we need to think of a different way that the banner can push additional content down. I hope this would be a different CSS setting but i'm not really sure!
