### ISSUE TITLE
Auto-syncing new translations (for all languages) from Transifex didn't work smoothly

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#9620]
I'm trying out the auto-PR generation in Transifex, for the #3262 wrap-up and #9257 projects for GSoC, and i tried running it, but got this error:

![image](https://user-images.githubusercontent.com/24359/117879402-f158a100-b274-11eb-8e64-1cd8e3b4d213.png)

```
 Some files didn’t sync with Transifex:
/config/locales/en.yml
Error while creating resource: b"Format 'YAML' not found"
/config/locales/ar.yml
Error while uploading translation: b'Not Found'
/config/locales/gr.yml
Error while uploading translation: b'Not Found'
/config/locales/de.yml
Error while uploading translation: b'Not Found'
```

To run it, i set up a config file like this:

```
filters:
  - filter_type: file
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: YAML
    source_language: en
    source_file: config/locales/en.yml
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: 'config/locales/<lang>.yml'
```

Then pressed Sync here:

![image](https://user-images.githubusercontent.com/24359/117879498-10efc980-b275-11eb-9efb-fd9d7a91447a.png)

I may have this wrong! Lets discuss, document, and debug, and smooth this process out, then make it clear for others to do!
